
package tela;
import Objetos.*;
import DaoDinamico.Dao;
/**
 * @author Felipe-Isoppo
 */
public class Tela01_Inicial extends javax.swing.JFrame {

    Dao dao = new Dao();
    Caixa caixa;
    /**
     * Creates new form Tela01_Inicial
     */
    
    public Tela01_Inicial() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btFuncionario = new javax.swing.JButton();
        btTerceirizado = new javax.swing.JButton();
        btCardapio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btExtratoVenda = new javax.swing.JButton();
        btEstoque = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        brAgenda = new javax.swing.JButton();
        btStatusPedido = new javax.swing.JButton();
        brRegistroAtendimento = new javax.swing.JButton();
        brCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial De Gestao da Pizzaria");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administração", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 12))); // NOI18N

        btFuncionario.setFocusable(false);
        btFuncionario.setLabel("Registro de Funcionários");
        btFuncionario.setName(""); // NOI18N
        btFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncionarioActionPerformed(evt);
            }
        });

        btTerceirizado.setFocusable(false);
        btTerceirizado.setLabel("Registro de Terceirizados");

        btCardapio.setFocusable(false);
        btCardapio.setLabel("Editar Cardápio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(btCardapio))
                    .addComponent(btTerceirizado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFuncionario)
                    .addComponent(btCardapio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btTerceirizado)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Financeiro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 12))); // NOI18N

        btExtratoVenda.setFocusable(false);
        btExtratoVenda.setLabel("Extrado de Vendas");

        btEstoque.setFocusable(false);
        btEstoque.setLabel("Controle de Estoque");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btExtratoVenda)
                .addGap(26, 26, 26)
                .addComponent(btEstoque)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExtratoVenda)
                    .addComponent(btEstoque))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atendimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 12))); // NOI18N

        brAgenda.setFocusable(false);
        brAgenda.setLabel("Pedidos Agendados");

        btStatusPedido.setFocusable(false);
        btStatusPedido.setLabel("Status dos Pedidos");

        brRegistroAtendimento.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        brRegistroAtendimento.setText("Registrar Atendimento");
        brRegistroAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brRegistroAtendimentoActionPerformed(evt);
            }
        });

        brCliente.setFocusable(false);
        brCliente.setLabel("Cadastro de Clientes");
        brCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brAgenda)
                    .addComponent(brCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brRegistroAtendimento)
                    .addComponent(btStatusPedido))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brAgenda)
                    .addComponent(btStatusPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brCliente)
                    .addComponent(brRegistroAtendimento))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("frame1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brRegistroAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brRegistroAtendimentoActionPerformed
        //Tela02_RegistroAtendimento.iniciarTela02();
        //dao.MontaPessoas();
        
        // criar nova instância da tela 2
        Tela02_RegistroAtendimento tela2 = new Tela02_RegistroAtendimento(this, true, dao);
        // associar o DAO da tela2 ao DAO desta janela(tela1) 
        this.dao = tela2.dao;
        // associar combobox para poder atualizar quando fechar a janela modal
        tela2.papai = this;
        // tornar a janela visível
        tela2.setVisible(true);
        //Caixa caixa = new Caixa();
        dao.SalvaCaixa(caixa);
        
    }//GEN-LAST:event_brRegistroAtendimentoActionPerformed

    private void brClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brClienteActionPerformed

        //Atendimento at = new Atendimento();
         // criar nova instância da tela 3
        Tela03_Atendimento telaPessoas = new Tela03_Atendimento(new javax.swing.JFrame(), true, new Atendimento(), dao,false);
        // associar o DAO da tela3 ao DAO desta janela(tela2) 
        this.dao = telaPessoas.dao;
        // associar combobox para poder atualizar quando fechar a janela modal
        telaPessoas.filho1 = this;
        // tornar a janela visível
        telaPessoas.setVisible(true);
        
        


        
    }//GEN-LAST:event_brClienteActionPerformed

    private void btFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncionarioActionPerformed

        
         // criar nova instância da tela 3
        Tela03_Atendimento telaStaff = new Tela03_Atendimento(new javax.swing.JFrame(), true, new Atendimento(0 , new Staff("cadastro")), dao,false);
        // associar o DAO da tela3 ao DAO desta janela(tela2) 
        this.dao = telaStaff.dao;
        // associar combobox para poder atualizar quando fechar a janela modal
        telaStaff.filho1 = this;
        // tornar a janela visível
        telaStaff.setVisible(true);



        
    }//GEN-LAST:event_btFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
      //Cliente x = new Cliente("eu", "000", "rua", "47" );
      //System.out.println("" + x.getNome() + x.getcpf() + x.getEndereco()+ x.getTelefone());
      //Servico x = new Servico(10, "000");
      //System.out.println("" + x.getPreco() + x.getDescricao() + x.getDataEntrega()+ x.getAgenda());
      
      //Tela02_RegistroAtendimento.iniciarTela02();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela01_Inicial().setVisible(true);}
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton brAgenda;
    javax.swing.JButton brCliente;
    javax.swing.JButton brRegistroAtendimento;
    javax.swing.JButton btCardapio;
    javax.swing.JButton btEstoque;
    javax.swing.JButton btExtratoVenda;
    javax.swing.JButton btFuncionario;
    javax.swing.JButton btStatusPedido;
    javax.swing.JButton btTerceirizado;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
