
package tela;

import javax.swing.DefaultListModel;
import DaoDinamico.Dao;
import Objetos.*;
import java.util.ArrayList;
/**
 * @author Felipe-Isoppo
 */
public class Tela03_Atendimento extends javax.swing.JDialog {
    static int id;
    /**
     * Creates new form Tela03_Atendimento
     */
    public Tela03_Atendimento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabel9.setText(String.valueOf(id));
        
        setLocationRelativeTo(null);
        // carrega o cardapio no combo box
        carregarCardapioNaLista(); 
        
        //cria uma lista vazia para adicionar os itens do pedido
        listPedido.setModel(new DefaultListModel());
    }
    // instância de acesso aos dados
    Dao dao = new Dao();
    int item = 1;
    int itemtela = 1;
    ArrayList<Oferta> pedido= new ArrayList();
    
    public void carregarCardapioNaLista() {
        // limpa itens
        comboBoxCardapio.removeAllItems();
        // preenche os livros
        for (Produto produtos : dao.retornarCardapio()) {
            comboBoxCardapio.addItem(produtos.getDescricao());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLCpf = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLFone = new javax.swing.JLabel();
        jLEndereco = new javax.swing.JLabel();
        jLObs = new javax.swing.JLabel();
        btSalvarPessoa = new javax.swing.JButton();
        btBuscarPessoa = new javax.swing.JButton();
        textCpf = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();
        textFone = new javax.swing.JTextField();
        textObs = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaEndereco = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listPedido = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLFuncionario = new javax.swing.JLabel();
        jLData = new javax.swing.JLabel();
        btCancelarItem = new javax.swing.JButton();
        jLCliente = new javax.swing.JLabel();
        btConlcuirAtendimento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btAtribuirClienteAoPedido = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxCardapio = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboBoxQtd = new javax.swing.JComboBox<>();
        btIncluirItemAoPedido = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        checkBoxRetirarNoBalcao = new javax.swing.JCheckBox();
        checkBoxDelivery = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atendimento");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 12))); // NOI18N

        jLCpf.setText("CPF:");

        jLNome.setText("Nome:");

        jLFone.setText("Fone:");

        jLEndereco.setText("Endereço:");

        jLObs.setText("Observação:");

        btSalvarPessoa.setText("Salvar");
        btSalvarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarPessoaActionPerformed(evt);
            }
        });

        btBuscarPessoa.setText("Buscar");

        textAreaEndereco.setColumns(20);
        textAreaEndereco.setRows(5);
        jScrollPane1.setViewportView(textAreaEndereco);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCpf)
                            .addComponent(jLNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCpf)
                            .addComponent(textNome)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLFone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFone))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLEndereco)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLObs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textObs)))
                .addGap(6, 6, 6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvarPessoa)
                .addGap(32, 32, 32)
                .addComponent(btBuscarPessoa)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCpf)
                    .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFone)
                    .addComponent(textFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLObs)
                    .addComponent(textObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarPessoa)
                    .addComponent(btBuscarPessoa)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro do Atendimento"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição do Pedido"));

        listPedido.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listPedido);

        jLabel4.setText("Item:");

        jLabel5.setText("Descrição:");

        jLabel6.setText("Quantidade:");

        jLabel7.setText("Valor( R$ ):");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLFuncionario.setText("Atendente:");

        jLData.setText("Data:");

        btCancelarItem.setBackground(new java.awt.Color(255, 255, 255));
        btCancelarItem.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btCancelarItem.setText("Cancelar Item Selecionado");
        btCancelarItem.setActionCommand("");
        btCancelarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarItemActionPerformed(evt);
            }
        });

        jLCliente.setText("Cliente:");

        btConlcuirAtendimento.setBackground(new java.awt.Color(255, 255, 255));
        btConlcuirAtendimento.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btConlcuirAtendimento.setText("Concluir Atendimeto");

        jLabel3.setText("Endereço:");

        jLabel8.setText("ID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btCancelarItem)
                                .addGap(28, 28, 28)
                                .addComponent(btConlcuirAtendimento, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 384, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCliente)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLFuncionario)
                                .addGap(150, 150, 150)
                                .addComponent(jLData)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLFuncionario)
                    .addComponent(jLabel9)
                    .addComponent(jLData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelarItem)
                    .addComponent(btConlcuirAtendimento)))
        );

        btAtribuirClienteAoPedido.setBackground(new java.awt.Color(255, 255, 255));
        btAtribuirClienteAoPedido.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btAtribuirClienteAoPedido.setText("=>");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cardápio"));

        jLabel1.setText("Item:");

        comboBoxCardapio.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxCardapio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Qtd.:");

        comboBoxQtd.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxQtd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        btIncluirItemAoPedido.setBackground(new java.awt.Color(255, 255, 255));
        btIncluirItemAoPedido.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btIncluirItemAoPedido.setText("Incluir Item ao Pedido");
        btIncluirItemAoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirItemAoPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxCardapio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btIncluirItemAoPedido)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btIncluirItemAoPedido)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Serviço"));

        checkBoxRetirarNoBalcao.setText("Retirar no Balcão");

        checkBoxDelivery.setText("Delivery");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxRetirarNoBalcao)
                    .addComponent(checkBoxDelivery))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxRetirarNoBalcao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxDelivery)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtribuirClienteAoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btAtribuirClienteAoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    this.dispose(); //retorna para a tela anterior e deve solicitar para fechar o caixa
    }//GEN-LAST:event_formWindowClosing

    private void btIncluirItemAoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirItemAoPedidoActionPerformed
        // buscar nome do item selecionado
        String produtoSelecionado = comboBoxCardapio.getSelectedItem().toString();
        // buscar quantidade do item selecionado
        int quantidadeSelecionada = Integer.parseInt(comboBoxQtd.getSelectedItem().toString(),10);

        //procura o produto no cardapio que possui a mesma descricao do item selecionado no combobox
        Produto prod = dao.buscarProduto(produtoSelecionado);
        
        //guarda o numero de ref do produto do cardapio;
        int itemMenu = prod.getItem();
        
        //altera a quantidade do estoque no Cardapio
        dao.retiraItemDoEstoque(itemMenu, quantidadeSelecionada);
        
        
        //cria uma lista temporaria
        DefaultListModel tmp = (DefaultListModel) listPedido.getModel();
        // adiciona no fim na lista auxiliar
        String x = String.format("%2d %-50s %-5s %10.2f", itemtela, produtoSelecionado, quantidadeSelecionada, prod.getPreco());
        tmp.add(tmp.getSize(), x);
        // reconfigurar itens da lista (inclui lista temporaria na tela)
        listPedido.setModel(tmp);
        
        
        
        //altera o valor do item para coincidir com o item do pedido e altera a quantidade, conforme pedido
        Oferta o = new Produto(item, prod.getPreco()*quantidadeSelecionada,prod.getDescricao()+" Qtd.: "+quantidadeSelecionada,quantidadeSelecionada,prod.getUnidade());
        //inclui item no pedido
        pedido.add(o);
        
        
        for (Oferta p : pedido){
            System.out.println(""+p.getItem()+ " "+p.getDescricao() + " Subtotal:" + p.getPreco());
        }
        
        
        //incrementa os itens do pedido
        item++;
        itemtela++;
       

        
        
        
        
    }//GEN-LAST:event_btIncluirItemAoPedidoActionPerformed

    private void btCancelarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarItemActionPerformed
        //identifica o item selecionado
        int posi = listPedido.getSelectedIndex();
        // criar lista auxiliar
        DefaultListModel tmp = (DefaultListModel) listPedido.getModel();
        // remove item selecionado da lista auxiliar
        tmp.remove(posi);
        // reconfigurar itens da lista (coloca lista auxiliar na tela)
        listPedido.setModel(tmp);
        
        //remove o item selecionado do arrayList pedido
        pedido = dao.removeItemPedido(posi, pedido);
        
        //pedido.remove(posi);
        
        for (Oferta p : pedido){
            System.out.println(""+p.getItem()+ " "+p.getDescricao() + " Subtotal:" + p.getPreco());
        }
        item--;
        
    }//GEN-LAST:event_btCancelarItemActionPerformed

    private void btSalvarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarPessoaActionPerformed
         
        // cria a nova pessoa
        Pessoa novaPessoa;
        if (textNome.getText().equals("")){
            if (textAreaEndereco.getText().equals("")){
                novaPessoa = (ClienteBalcao)new ClienteBalcao(textNome.getText(), textCpf.getText());
            }else{
                novaPessoa = (Cliente)new Cliente(textNome.getText(), textCpf.getText(), textFone.getText(), textAreaEndereco.getText());
            }  
        }else{
            novaPessoa = (Staff)new Staff(textNome.getText(), textCpf.getText(), textFone.getText(), textAreaEndereco.getText(), textObs.getText());
        }
        
        
        
        //  cadastra pessoa
        if (!dao.existePessoaPorCPF(textCpf.getText())) {
            // adicionar a nova pessoa
            dao.adicionarPessoa(novaPessoa);
        } else { // atualiza cadastro da pessoa
            dao.atualizarPessoa(novaPessoa);
            
        }
        
        
        
        
        
    }//GEN-LAST:event_btSalvarPessoaActionPerformed

    public static void iniciarTela03(int idAtendimento) {
        id = idAtendimento;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela03_Atendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela03_Atendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela03_Atendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela03_Atendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela03_Atendimento(new javax.swing.JFrame(), true).setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtribuirClienteAoPedido;
    private javax.swing.JButton btBuscarPessoa;
    private javax.swing.JButton btCancelarItem;
    private javax.swing.JButton btConlcuirAtendimento;
    private javax.swing.JButton btIncluirItemAoPedido;
    private javax.swing.JButton btSalvarPessoa;
    private javax.swing.JCheckBox checkBoxDelivery;
    private javax.swing.JCheckBox checkBoxRetirarNoBalcao;
    private javax.swing.JComboBox<String> comboBoxCardapio;
    private javax.swing.JComboBox<String> comboBoxQtd;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLCpf;
    private javax.swing.JLabel jLData;
    private javax.swing.JLabel jLEndereco;
    private javax.swing.JLabel jLFone;
    private javax.swing.JLabel jLFuncionario;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLObs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listPedido;
    private javax.swing.JTextArea textAreaEndereco;
    private javax.swing.JTextField textCpf;
    private javax.swing.JTextField textFone;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textObs;
    // End of variables declaration//GEN-END:variables
}
